package com.neolab.crm.shared.resources;

public enum Option {
	
	ADD_TASK,
	ASSIGN_TASK,
	CHANGE_TASK_STATUS,
	REMOVE_FROM_PROJECT,
	CREATE_PROJECT,
	ADD_USERS_TO_PROJECT,
	EDIT_PROJECT,
	EDIT_USER,
	WRITE_NEWS,
	WRITE_PROJECT_NEWS,
	UPLOAD_DOCUMENT, INVITE_USER, CREATE_CATEGORY
}
